name: "🆘 Owner Help Request"
description: "Owners can use this template to raise issues on behalf of others who need help. (Visible to owners only)"
title: "HELP: <Brief description of the issue>"
labels: ["help wanted", "status: needs triage"]
body:
  - type: input
    id: requester_name
    attributes:
      label: "Requester Name"
      description: "Name of the person requesting help."
      placeholder: "E.g., John Doe"
    validations:
      required: true

  - type: input
    id: requester_contact
    attributes:
      label: "Requester Contact"
      description: "Contact information of the person requesting help."
      placeholder: "E.g., john.doe@example.com"
    validations:
      required: true

  - type: textarea
    id: issue_summary
    attributes:
      label: "Issue Summary"
      description: "Provide a summary of the issue."
      placeholder: "E.g., Unable to access the dashboard"
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: "Issue Description"
      description: "Describe the issue in detail."
      placeholder: "Provide a detailed description of the issue, including steps to reproduce, expected behavior, and actual behavior..."
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context (Optional)"
      description: "Add any other context or information that might be relevant to this issue."
      placeholder: "Provide any extra details, screenshots, or references that could help with understanding the issue..."

  - type: checkboxes
    id: agreement
    attributes:
      label: "Agreement"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true

  - type: markdown
    attributes:
      value: |
        **Thank you for raising this help request!** We will review the issue promptly and provide assistance as soon as possible. 🙏
