name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  close-stale-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            const staleIssues = issues.filter(issue => {
              const createdAt = new Date(issue.created_at);
              const now = new Date();
              const oneWeek = 7 * 24 * 60 * 60 * 1000;
              return (now - createdAt) > oneWeek && !issue.pull_request;
            });

            for (const issue of staleIssues) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: 'This issue is being closed due to inactivity. No pull request was raised within a week.'
              });

              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              });
            }
