name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  close-stale-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is being marked as stale due to inactivity.'
          stale-pr-message: 'This pull request is being marked as stale due to inactivity.'
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: 'Stale'
          stale-pr-label: 'Stale'
          remove-stale-when-updated: true
          only-labels: ''
          exempt-issue-labels: ''
          exempt-pr-labels: ''
          operations-per-run: 30
          remove-issue-stale-when-updated: true
          remove-pr-stale-when-updated: true
          close-issue-message: 'This issue is being closed due to inactivity. No pull request was raised within a week.'
          close-pr-message: 'This pull request is being closed due to inactivity. No updates were made within a week.'
