name: PR Description Check

on:
  pull_request:
    types: [opened, edited]

permissions:
  pull-requests: write

jobs:
  validate-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Validate PR Description
        id: validate
        run: |
          if [ -z "${{ github.event.pull_request.body }}" ]; then
            echo "Pull request description is empty. Please provide a description."
            exit 1
          fi

      - name: Set PR status
        if: steps.validate.outcome == 'failure'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "❌ Pull request description is empty. Please provide a description."